version: '3.8'
services:
  crm-api:
    container_name: crm-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
        - .env.example
    ports:
     - "8000:80"
    tty: true
    volumes:
     - ./:/opt/crm-api
     - /opt/crm-api/vendor
     - /opt/crm-api/node_modules
    networks:
     - crm_api
    command: "/bin/sh /opt/crm-api/scripts/entrypoint.sh"
  db:
      image: mysql:latest
      container_name: mysql-container
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=laravel
          - MYSQL_USER=user
          - MYSQL_PASSWORD=my-secret-pw
          - MYSQL_PORT=3306
      ports:
          - "3306:3306"
      networks:
          - crm_api
networks:
  crm_api:
    name: crm_api
